version: '2'

services:
  mootse-mariadb:
    container_name: mootse-mariadb
    env_file: .env
    image: docker.io/library/mariadb:10.4
    restart: always
    healthcheck:
      test: '/usr/local/bin/healthcheck.sh --su-mysql --connect --innodb_initialized'
    networks:
      - mootse-network

  mootse-runner:
    container_name: mootse-runner
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mootse-mariadb
    restart: always
    healthcheck:
      test: 'python healthcheck.py'
    networks:
      - mootse-network

networks:
  mootse-network:
